name: id
version: 1.0.1
author: Daniel Davidson <dbdavidson@yahoo.com>
homepage: https://github.com/patefacio/id
description: >
  Library for consistent usage of identifiers
dependencies:
  logging: ">=0.7.1"

# custom <id dependencies>
# end <id dependencies>

dev_dependencies:
  hop: ">=0.27.0"

# custom <id dev dependencies>

environment: 
  sdk: ">=0.8.10+6 <2.0.0" 

# end <id dev dependencies>

transformers:
# custom <id transformers>
# end <id transformers>

