name: id
version: 1.0.17
author: Daniel Davidson <dbdavidson@yahoo.com>
homepage: https://github.com/patefacio/id
description: >
  library_ for consistent usage of identifiers
environment:
  sdk: '>=2.0.0-dev.61 <3.0.0'

dependencies:

# custom <id dependencies>

  collection: "1.14.11"
  quiver: "2.0.0+1"
  logging: "0.11.3+2"

# end <id dependencies>

dev_dependencies:

# custom <id dev dependencies>

  test: "1.3.0"

# end <id dev dependencies>

dependency_overrides:
# custom <id dependency overrides>
# end <id dependency overrides>

transformers:

# custom <id transformers>
# end <id transformers>

