name: id
version: 0.0.3
author: Daniel Davidson <dbdavidson@yahoo.com>
homepage: https://github.com/patefacio/id
description: >
  Library for consistent usage of identifiers
dependencies:
  logging: ">=0.7.1"

# custom <id dependencies>
# end <id dependencies>

dev_dependencies:
  hop: ">=0.24.4"

# custom <id dev dependencies>
# end <id dev dependencies>


