name: id
version: 0.0.1
author: Daniel Davidson <dbdavidson@yahoo.com>
homepage: https://github.com/patefacio/id
description: >
  Library for consistent usage of identifiers
dependencies:
  logging:  "any"
  logging_handlers:  "any"
# custom <id dependencies>
# end <id dependencies>

