name: id
version: 1.0.2
author: Daniel Davidson <dbdavidson@yahoo.com>
homepage: https://github.com/patefacio/id
description: >
  Library for consistent usage of identifiers
dependencies:
  logging: ">=0.7.1"

# custom <id dependencies>
  quiver: ">=0.18.0<0.19.0"
# end <id dependencies>

dev_dependencies:
  unittest: ">=0.9.0 < 0.10.0"
  browser: "any"
  hop: ">=0.27.0"
  hop_docgen: ">=0.1.0 <0.2.0"

# custom <id dev dependencies>
  ebisu: "any"
# end <id dev dependencies>

transformers:

# custom <id transformers>
# end <id transformers>

