name: id
version: 1.0.17
author: Daniel Davidson <dbdavidson@yahoo.com>
homepage: https://github.com/patefacio/id
description: >
  Library for consistent usage of identifiers
environment:
  sdk: '>=1.8.2 <2.0.0'

dependencies:

# custom <id dependencies>
  collection: "^1.1.0"
  quiver: ">=0.21.0<0.25.0"
  logging: ">=0.9.3<0.12.0"
# end <id dependencies>

dev_dependencies:

# custom <id dev dependencies>

  test: ">=0.12.0 < 0.14.0"
  ebisu: "^0.7.4"

# end <id dev dependencies>

dependency_overrides:
# custom <id dependency overrides>
# end <id dependency overrides>

transformers:

# custom <id transformers>
# end <id transformers>

