name: id
version: 1.0.12
author: Daniel Davidson <dbdavidson@yahoo.com>
homepage: https://github.com/patefacio/id
description: >
  Library for consistent usage of identifiers
dependencies:

# custom <id dependencies>
  collection: "^1.1.0"
  quiver: ">=0.21.0<0.22.0"
  logging: ">=0.9.3<0.10.0"  
# end <id dependencies>

dev_dependencies:
  yaml: "any"
  browser: "any"
  hop: "any"
  hop_docgen: "any"

# custom <id dev dependencies>

  test: "^0.12.0"

# end <id dev dependencies>

dependency_overrides:
# custom <id dependency overrides>

#  ebisu:
#    path: /home/dbdavidson/dev/open_source/ebisu

environment:
  sdk: ">=1.8.0 <2.0.0"
    
# end <id dependency overrides>

transformers:

# custom <id transformers>
# end <id transformers>

