name: id
version: 0.0.1
author: Daniel Davidson <dbdavidson@yahoo.com>
homepage: https://github.com/patefacio/id
description: >
  Library for consistent usage of identifiers
dependencies:
  logging: ">=0.6.21+3 <0.6.22"

  logging_handlers: ">=0.5.0+3 <0.5.1"

# custom <id dependencies>
# end <id dependencies>

dev_dependencies:
  hop: "0.24.2"

# custom <id dev dependencies>
# end <id dev dependencies>


