name: id
version: 1.0.4
author: Daniel Davidson <dbdavidson@yahoo.com>
homepage: https://github.com/patefacio/id
description: >
  Library for consistent usage of identifiers
dependencies:

# custom <id dependencies>
  quiver: ">=0.18.0<0.19.0"
  logging: ">=0.9.3<0.10.0"  
# end <id dependencies>

dev_dependencies:
  unittest: ">=0.11.0 < 0.12.0"
  browser: "any"
  hop: "any"
  hop_docgen: "any"

# custom <id dev dependencies>
  ebisu: "any"
# end <id dev dependencies>

dependency_overrides:
# custom <id dependency overrides>
# end <id dependency overrides>

transformers:

# custom <id transformers>
# end <id transformers>

